main: eu.savagecore.perworldresourcepack.PerWorldResourcePack
version: 0.1.0-SNAPSHOT
name: PerWorldResourcePack
author: SavageCore
website: https://savagecore.eu
database: false
description: Per world resource packs
commands:
  pwrp:
    aliases:
    - perworldresourcepack
  pwrp help:
    description: Display Usage Tips
    usage: /pwrp help
    aliases:
    - perworldresourcepack help
    permission: perworldresourcepack.help    
  pwrp clear:
    description: Clear resource pack of world
    usage: /pwrp clear <world_name>
    aliases:
    - perworldresourcepack clear
    permission: perworldresourcepack.clear       
  pwrp debug:
    description: Toggle debug mode
    usage: /pwrp debug <true|false>
    aliases:
    - perworldresourcepack debug
    permission: perworldresourcepack.debug    
  pwrp set default:
    description: Set default resource pack
    usage: /pwrp set default <url>
    aliases:
    - perworldresourcepack set default
    permission: perworldresourcepack.set.default     
  pwrp set world:
    description: Set resource pack of world
    usage: /pwrp set world <url> <world_name>
    aliases:
    - perworldresourcepack set default
    permission: perworldresourcepack.set.world.*       
permissions:
  perworldresourcepack.*:
    default: op
    children:
      perworldresourcepack.clear: true
      perworldresourcepack.debug: true
      perworldresourcepack.set.default: true
      perworldresourcepack.set.world.*: true
  perworldresourcepack.clear:
    description: Clear Resource Pack for World
    default: false
  perworldresourcepack.debug:
    description: Toggle debug output in console on or off
    default: false
  perworldresourcepack.help:
    description: Print usage.
    default: true
  perworldresourcepack.set.default:
    description: Set default Resource Pack.
    default: false
  perworldresourcepack.set.world.*:
    description: Set Resource Pack for World.
    default: false
  perworldresourcepack.bypass.world.*:
    descripion: Bypass resource pack loading
    default: false